apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cache
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: "localhost:6380"
    - name: redisPassword
      value: ""
    - name: actorStateStore
      value: "false"
    - name: ttlInSeconds
      value: "3600"
scopes:
  - user-service

