#!/bin/bash
# Generate docker-compose configuration with N PostgreSQL read replicas
# Usage: ./generate-postgres-replicas.sh [replica_count] [output_file]
# Example: ./generate-postgres-replicas.sh 3 docker-compose.replicas.yml

set -e

REPLICA_COUNT=${1:-2}
OUTPUT_FILE=${2:-docker-compose.replicas.yml}

echo "Generating docker-compose configuration with $REPLICA_COUNT replicas..."

# Generate replica service definitions
REPLICA_SERVICES=""
REPLICA_VOLUMES=""
PGPOOL_BACKENDS="PGPOOL_BACKEND_HOSTNAME0: postgres-primary
    PGPOOL_BACKEND_PORT0: 5432
    PGPOOL_BACKEND_WEIGHT0: 0
    PGPOOL_BACKEND_FLAG0: ALLOW_TO_FAILOVER"

for i in $(seq 1 $REPLICA_COUNT); do
  REPLICA_SERVICES+="
  postgres-replica-${i}:
    image: postgres:15
    container_name: postgres-replica-${i}
    restart: unless-stopped
    environment:
      POSTGRES_USER: dapruser
      POSTGRES_PASSWORD: daprpassword
      POSTGRES_DB: daprdb
      PGUSER: postgres
      REPLICA_NUMBER: ${i}
    volumes:
      - postgres_replica${i}_data:/var/lib/postgresql/data
      - ./scripts/postgres-replica-init.sh:/docker-entrypoint-initdb.d/init-replica.sh
    command: >
      postgres
      -c hot_standby=on
      -c max_standby_streaming_delays=30s
    depends_on:
      postgres-primary:
        condition: service_healthy
    healthcheck:
      test: [\"CMD-SHELL\", \"pg_isready -U dapruser -d daprdb && pg_is_in_recovery\"]
      interval: 10s
      timeout: 5s
      retries: 5"

  REPLICA_VOLUMES+="
  postgres_replica${i}_data:"

  # Add to PgPool backends
  PGPOOL_BACKENDS+="
    PGPOOL_BACKEND_HOSTNAME${i}: postgres-replica-${i}
    PGPOOL_BACKEND_PORT${i}: 5432
    PGPOOL_BACKEND_WEIGHT${i}: 1
    PGPOOL_BACKEND_FLAG${i}: ALLOW_TO_FAILOVER"
done

# Generate the docker-compose file
cat > "$OUTPUT_FILE" <<EOF
# Auto-generated docker-compose file with $REPLICA_COUNT PostgreSQL read replicas
# Generated by: ./scripts/generate-postgres-replicas.sh $REPLICA_COUNT
# To regenerate: ./scripts/generate-postgres-replicas.sh [count] [output_file]

services:
  # PostgreSQL Primary (Master)
  postgres-primary:
    image: postgres:15
    container_name: postgres-primary
    restart: unless-stopped
    environment:
      POSTGRES_USER: dapruser
      POSTGRES_PASSWORD: daprpassword
      POSTGRES_DB: daprdb
      POSTGRES_REPLICATION_USER: replicator
      POSTGRES_REPLICATION_PASSWORD: replicator_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_primary_data:/var/lib/postgresql/data
      - ./scripts/postgres-primary-init.sh:/docker-entrypoint-initdb.d/init-replication.sh
    command: >
      postgres
      -c wal_level=replica
      -c max_wal_senders=$((REPLICA_COUNT + 2))
      -c max_replication_slots=$((REPLICA_COUNT + 2))
      -c hot_standby=on
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dapruser -d daprdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL Read Replicas
${REPLICA_SERVICES}

  # PgPool-II - Connection Pooler with Read/Write Splitting
  pgpool:
    image: pgpool/pgpool:latest
    container_name: pgpool
    restart: unless-stopped
    environment:
${PGPOOL_BACKENDS}
      PGPOOL_POSTGRES_USERNAME: dapruser
      PGPOOL_POSTGRES_PASSWORD: daprpassword
      PGPOOL_POSTGRES_DBNAME: daprdb
      PGPOOL_ENABLE_LOAD_BALANCING: "yes"
      PGPOOL_NUM_INIT_CHILDREN: 32
      PGPOOL_MAX_POOL: 4
    ports:
      - "5433:5432"
    depends_on:
      postgres-primary:
        condition: service_healthy
      $(for i in $(seq 1 $REPLICA_COUNT); do echo "postgres-replica-${i}:"; echo "        condition: service_healthy"; done | sed '$!N;s/\n/ /')
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "5432", "-U", "dapruser"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_primary_data:${REPLICA_VOLUMES}
EOF

echo "✅ Generated $OUTPUT_FILE with $REPLICA_COUNT replicas"
echo ""
echo "To use this configuration:"
echo "  1. Make sure scripts/postgres-primary-init.sh exists"
echo "  2. Make sure scripts/postgres-replica-init.sh exists"
echo "  3. Run: docker-compose -f $OUTPUT_FILE up -d"
echo ""
echo "Your application should connect to: postgresql://dapruser:daprpassword@pgpool:5432/daprdb"
echo "PgPool-II will automatically route writes to primary and reads to replicas!"

